### ISSUE TITLE
How to implement a continuous action space?

### ISSUE THREAD

**Issue by stabilus** [AminHP/gym-anytrading#11]
say I wanted to train actions to be in a range between 0 and 1, whereby the number represents the percentage of the networth I should be invested in the asset. The resulting action is then to buy or sell the difference.

**Comment by AminHP** [comment]
To have a continuous action space, we need to rewrite all the three environments. Personally, I like this idea and I am up to implement `continuous_trading_env`, `continuous_forex_env`, and `continuous_stocks_env`. But, I'm not sure if I have enough time for that at this moment.

I was thinking about having a range between -1 and +1 for action values. The range -1 to 0 indicates a sell signal while the range 0 to +1 indicates a buy signal. Also, the absolute value of that can represent the percentage of the networth and multiply [`self._total_profit`](https://github.com/AminHP/gym-anytrading/blob/master/gym_anytrading/envs/stocks_env.py#L60) for the next trade. What do you think?

**Comment by stabilus** [comment]
It would probably be simpler if you just used 0-1 and let the algo decide whether that means buying or selling. i.e. if you're invested 50%, an action of 0.3 would imply selling the position from a percentage of 50% down to 30%.

**Comment by xicocaio** [comment]
Hello @AminHP ,

First of all, great work on this project as it is proving to be very useful to me.

I also prefer the [-1, +1] range for the continuous case as it usually the most common in the research community.

On a similar note, for the discrete case, how do you recommend extending the TradingEnv class to define my action values?

Thanks in advance =)

**Comment by AminHP** [comment]
Hi @xicocaio, I'm glad it's been useful to you :)

Thanks for the information. I will consider it.

I don't exactly understand your question. Do you want to extend the `TradingEnv` to support more than just two actions? For example, you want to have 4 discrete actions, right?

**Comment by xicocaio** [comment]
Hi,

My issue is that I want to extend `TradingEnv,` but I want to use other values. Or even add other actions, as such:

```
class Actions(Enum):
    Sell = -1
    Hold = 0
    Buy = 1
```

Then, because these actions are in the base class, I found it not very practical to extend them in a subclass.

So my question is about what do you think is the best way I could deal with that.

Tks!

**Comment by AminHP** [comment]
@xicocaio Yes you are right, this is a fundamental change and affects almost all parts of the trading environments (both logic and rendering). So, I think it is better to fork and rewrite those parts according to your custom actions.

**Comment by xicocaio** [comment]
Ok, I will do that, Thank you!

**Comment by luccosta** [comment]
> ```
> class Actions(Enum):
>     Sell = -1
>     Hold = 0
>     Buy = 1
> ```

@xicocaio I was using this format, but my model just holds. Something similar happened with you?

**Comment by xicocaio** [comment]
@luccosta Well, it depends on how do you want your env and model to work.

In my case, I had to follow a specific design of a specific [scientific paper](https://papers.nips.cc/paper/1998/file/4e6cd95227cb0c280e99a195be5f6615-Paper.pdf), and so I had to fork this repo to make adjustments [here](https://github.com/xicocaio/gym-anytrading/tree/feat-moody_env) (changes are at the feat-moody_env branch).

In summary, when adopting continuous actions, you have to take into account what @AminHP said:

> I was thinking about having a range between -1 and +1 for action values. The range -1 to 0 indicates a sell signal while the range 0 to +1 indicates a buy signal. Also, the absolute value of that can represent the percentage of the networth and multiply self._total_profit for the next trade.

Also, you have to think about how these changes impact how you calculate the return (additive or multiplicative) as described in the mentioned paper.

**Comment by AminHP** [comment]
I just released a new project that supports the required feature.

https://github.com/AminHP/gym-mtsim

**Comment by kmafutah** [comment]
Thanks will be trying it out this weekend and will provide feedback. Once again thanks

Rgds
KM
