### ISSUE TITLE
PIP package not updated

### ISSUE THREAD

**Issue by nicola-pesavento** [AminHP/gym-anytrading#12]
This issue is just to notify that [PIP package](https://pypi.org/project/gym-anytrading/#history) is not updated, it's still at the first commit dated 22/09/2019.

**Comment by AminHP** [comment]
Thanks for reminding. I will update it soon.

**Comment by nicola-pesavento** [comment]
Thanks to you.

**Comment by AminHP** [comment]
Done! Good Luck!

https://github.com/AminHP/gym-anytrading/releases/tag/v1.1.0
