### ISSUE TITLE
How do you use your init.py to register it to gym?

### ISSUE THREAD

**Issue by toksis** [AminHP/gym-anytrading#14]
How to register gym-anytrading env to Gym? 

I see that you have the _init_.py. How do you do this? 

Thank you,
Vic

**Comment by AminHP** [comment]
When you import `gym_anytrading`, Python will automatically import the `__init__.py` file in the root directory of the module. So, all you need is just importing the module and it will be registered in the `gym` automatically.

**Comment by toksis** [comment]
Oh! thank you!
