### ISSUE TITLE
[QUESTION] Error in TradeEnv running check_env() from stable baselines

### ISSUE THREAD

**Issue by simonesalvucci** [AminHP/gym-anytrading#2]
Hi there,

I've encountered an issue running the following code:
```python3
import gym
from gym_anytrading.envs import TradingEnv, ForexEnv, Actions, Positions 
from gym_anytrading.datasets import FOREX_EURUSD_1H_ASK
from stable_baselines.common.env_checker import check_env


env = gym.make('forex-v0', frame_bound=(10, 500), window_size=10)
check_env(env, warn=False, skip_render_check=False)
````

The output I get is:
`AssertionError: The observation returned by the reset() method does not match the given observation space`

I've debugged your `TradingEnv` class and did't see any issue, so I've thought the problem could be in `check_env()`.

I've debugged `check_env()` as well, but everything seems fine there.
Then I went for the last test which was running `check_env()` with the classic `CartPole-v0` from gym, here `check_env()` didn't trow any exception  and run smoothly. 

This is the code for the `CartPole-v0`:
```python3
import gym
from gym.envs.classic_control import CartPoleEnv
from stable_baselines.common.env_checker import check_env

env = gym.make('CartPole-v0')
check_env(env, warn=False, skip_render_check=False)
```

Do you have any clue why this is happening? I'm confused lol

**Comment by simonesalvucci** [comment]
I've just realised I didn't reset the environment before running `check_env()`
Doing that solves the issue.

**Comment by simonesalvucci** [comment]
Actually I was wrong, resetting the environment doesn't solve the issue.
Sorry about that...

**Comment by AminHP** [comment]
Hi.

It was a small bug and I fixed it. Thank you!

**Comment by simonesalvucci** [comment]
The fix solves the issue, thank you!
