### ISSUE TITLE
What is the purpose of this code? len(frame_bound) == 2 (Question)

### ISSUE THREAD

**Issue by toksis** [AminHP/gym-anytrading#23]
What is the purpose of this code in forex_env? 
assert len(frame_bound) == 2? I am getting this error.
What is the purpose of that? my parameters are window_size:  10  frame_bound:  (50, 100)

```python
 def __init__(self, df, window_size, frame_bound, unit_side='left'):
        
        print("df: ",df," window_size: ",window_size," frame_bound: ", frame_bound)
        assert len(frame_bound) == 2
        assert unit_side.lower() in ['left', 'right']

        self.frame_bound = frame_bound
        self.unit_side = unit_side.lower()
        super().__init__(df, window_size)

        self.trade_fee = 0.0003  # unit
```

**Comment by toksis** [comment]
So the error is how to add the parameter frame bound in Visual studio code.

**Comment by AminHP** [comment]
This line of code only checks that you pass a tuple/list of size 2. It shouldn't give an error if your frame_bound is (50, 100).

**Comment by toksis** [comment]
Thank you
