### ISSUE TITLE
Using this environment for Course Project

### ISSUE THREAD

**Issue by kunal15** [AminHP/gym-anytrading#27]
Hi @AminHP ,

I wanted to use this environment as a part of my course project for RL. So, I wanted to ask you if anything has been implemented in this environment prior to this. And if possible if you can give me some resources of algorithms implemented for this environment.

Best,
Kunal

**Comment by AminHP** [comment]
Hi @kunal15.

I don't know much about what you are looking for, but I implemented an example [here](https://github.com/AminHP/gym-anytrading/blob/master/examples/a2c_quantstats.ipynb). I don't know if it is useful for you.

Also, I've seen some works on this env in the forked repositories. Maybe you can find something useful there.

Furthermore, this [issue](https://github.com/AminHP/gym-anytrading/issues/16) might give you some relevant information.
