### ISSUE TITLE
Question: TODO on price validation

### ISSUE THREAD

**Issue by jjphung** [AminHP/gym-anytrading#30]
@AminHP First off, thank you for your amazing work on this. This has been very helpful for my understanding.

This is just a question on the TODO comment located in the `stocks_env` line 21 [link](https://github.com/AminHP/gym-anytrading/blob/master/gym_anytrading/envs/stocks_env.py) and `forex_env` line 22 [link](https://github.com/AminHP/gym-anytrading/blob/master/gym_anytrading/envs/forex_env.py). 

What did you have in mind for "validating the indices"? Thank you.

**Comment by AminHP** [comment]
Hi @jjphung, Thanks! I'm glad it was helpful :)

Well, I was thinking of some special cases. For example, what should happen if `frame_bound` contains negative values or `frame_bound[0] - window_size` is negative?

But eventually, I concluded that it is unworthy to spend time on those exceptions.

**Comment by jjphung** [comment]
I was thinking the same thing and also came to the same conclusion before posting this question. Just wanted to run this by you if there was something else I missed. Thanks! 

Closing this issue.
