### ISSUE TITLE
Multi-asset datasets

### ISSUE THREAD

**Issue by woj-i** [AminHP/gym-anytrading#32]
Do you plan to support multi-asset datasets?

**Comment by AminHP** [comment]
What do you mean by "multi-asset datasets"? Can you explain your thoughts a bit more?

**Comment by woj-i** [comment]
I mean multiple stock in one dataset, like I put Amazon, MS, Uber in one dataset and learning process and decisions are made on all assets at particular point in time.
Definition: https://www.investopedia.com/terms/m/multiasset_class.asp
Example: https://github.com/Kismuz/btgym/blob/master/examples/multi_discrete_setup_intro.ipynb
More complex example of portfolio optimization: https://github.com/Kismuz/btgym/blob/master/examples/portfolio_setup_BETA.ipynb

**Comment by toksis** [comment]
This only trains for a single stock.

**Comment by AminHP** [comment]
Sorry for my late response. I think this can be a valuable feature. I also have some ideas to implement it, but unfortunately, I don't have enough time for that at the moment.

Thanks for the suggestion. It will be the next feature to implement.

**Comment by lasys** [comment]
Any progress?

**Comment by AminHP** [comment]
I decided to leave this project as is, because it's simple and suitable for beginners. But I'm working on a new project to support such features and will publish it in a few months.

**Comment by QuantumCrazy** [comment]
Hi @AminHP are you planning on making an env suitable for crypto?

**Comment by AminHP** [comment]
Hi @QuantumCrazy 

I think the forex env is suitable. For example, you can use BTC/USD or ETH/BTC pairs.

**Comment by AminHP** [comment]
I just released a new project that supports the required features.
@woj-i @toksis @lasys @QuantumCrazy 

https://github.com/AminHP/gym-mtsim
