### ISSUE TITLE
stable-basellines3 example

### ISSUE THREAD

**Issue by highbulb** [AminHP/gym-anytrading#33]
It will be very helpful if you can point me some examples using stable-baselines3. I am still not sure how it comparable to stable-baselines as they have big warning box to compare performance. Appreciated.

**Comment by AminHP** [comment]
According to [this](https://github.com/DLR-RM/stable-baselines3#implemented-algorithms) table, **recurrent** networks are not supported yet for A2C. You should use other policies like `MlpPolicy`. To make [this](https://github.com/AminHP/gym-anytrading/blob/master/examples/a2c_quantstats.ipynb) example work with `stable-baselines3`, put the code below in the section `Train Env`:

```python
model = A2C('MlpPolicy', env, verbose=1)
model.learn(total_timesteps=1000)
```
