### ISSUE TITLE
Muzero Integration

### ISSUE THREAD

**Issue by mcisback** [AminHP/gym-anytrading#34]
Hello, i was trying to integrate gym anytrading with muzero-general, but i got this error:
`File "Development/Python/Muzero-GymAnytrading/self_play.py", line 137, in play_game
    ), f"Observation should be 3 dimensionnal instead of len(n_obs): {len(n_obs)} dimensionnal. Got observation of shape: n_obs: {n_obs}"
AssertionError: Observation should be 3 dimensionnal instead of len(n_obs): 4 dimensionnal. Got observation of shape: n_obs: (1, 1, 10, 2)`

Do you know what it means and how to resolve it?

Thank you,
Marco.

**Comment by AminHP** [comment]
Hi @mcisback, can you upload an example code?
