### ISSUE TITLE
Reward computation for stockEnv

### ISSUE THREAD

**Issue by sabeaussan** [AminHP/gym-anytrading#38]
Hi AminHp,

Really great work, the code is very pleasant to read. I have a question regarding the _calculate_reward function in the StocksEnvs : why is the step_reward only updated when we sell a long position ? As I understand buying after a short position should also generate profit/a loss and thus the agent should be rewarded accordingly but it is not taken into account if i'm correct. Forgive me if this is a noob question, I just got into finance and  stock trading yesterday.

Best regards,

**Comment by AminHP** [comment]
Hi @sabeaussan 

Thank you I'm glad it was helpful :)

In some markets only long trades are profitable. But it is possible to use the reward/profit function implemented in the ForexEnv if you want to make short trades profitable.
