### ISSUE TITLE
TF-Agents Implementation Example

### ISSUE THREAD

**Issue by Hsgngr** [AminHP/gym-anytrading#42]
Is it possible to create an implementation for TF-Agents also ?

**Comment by AminHP** [comment]
Hi @Hsgngr 

I'm not familiar with TF-Agents but I found this [link ](https://github.com/tensorflow/agents/blob/master/tf_agents/environments/suite_gym.py)helpful. It's a wrapper for Gym environments.

**Comment by Hsgngr** [comment]
Thank you so much, I tried with gym wrapper but TF-agents was a bit too complex for me to use.
