### ISSUE TITLE
What is total_reward and total_profit

### ISSUE THREAD

**Issue by 2796gaurav** [AminHP/gym-anytrading#45]
Hi, I was going over the code where when we render our results we get the result benchmarks such as 

`info {'total_reward': 8.100000000000023, 'total_profit': 0.7996927239889693, 'position': 1}`

I just want to know what these parameters mean espically total_reward and total_profit.

**Comment by AminHP** [comment]
Hi @2796gaurav,

According to [this](https://github.com/AminHP/gym-anytrading/blob/master/gym_anytrading/envs/trading_env.py#L94) line of code, they represent the total profit/reward earned by the agent at the end of  each step.
