### ISSUE TITLE
Next Steps

### ISSUE THREAD

**Issue by lachocki** [AminHP/gym-anytrading#46]
After a good bit of looking I haven't been able to find a way to illustrate what the training process has come up with so that I can take it into next steps and write a trading script to use the methodology/model the computer came up with. 

With custom imported data I've been able to get relatively consistent 'Explained Variance' close to 1. Which to my knowledge, means that the model and the actual data have very small discrepencies. Meaning the model could potentially be used to make a trading methodology that will have perhaps consistent wins. 

My trouble is seeing what exactly the contents of the model the computer came up with. Using quant-stats I can easily see its performance over the test period but that's not quite as useful as seeing how exactly the computer traded to be able to achieve quoted return data.

Any guidance or advice would be appreciated!

**Comment by AminHP** [comment]
Understanding how exactly the computer trades and what it learns requires a significant amount of knowledge about Neural Networks, Deep Learning, and  Reinforcement Learning. Besides, it needs so much work and investigation on different parts of the model. Maybe you can find some methods and tricks in easy and famous problems such as MNIST. After all, I don't think there would be an easy way for it.
