### ISSUE TITLE
Holding 0 position shall be encouraged when price is falling.

### ISSUE THREAD

**Issue by GXY2017** [AminHP/gym-anytrading#57]
Suggest adding this part in Stock.env()_calculate_reward(self, action).
Holding 0 position, eg, holding cash,  shall be encouraged when price is falling；or be punished when price is rising.

This will change reward, but will not affect profit if stock strategy is long only. 

````
            # encourage 0 holdings when price is falling
            if self._position == Positions.Short:
                step_reward += -price_diff
````

**Comment by AminHP** [comment]
Hi @GXY2017, thank you for the suggestion.

This project was supposed to be a simple baseline for beginners when I started it. So, I think it is better to keep it that way. However, you can inherit from the `StocksEnv` class and add your improvement.

**Comment by GXY2017** [comment]
Thank you for the reply.  Its a very clean learning example. 
Close this here.
