### ISSUE TITLE
Target variable (1 day ahead) or contemporaneous?

### ISSUE THREAD

**Issue by ChiragMirani** [AminHP/gym-anytrading#61]
Hello, 
   Is the target stock price 1 day forward in terms of training.  Because, the data we observe will be lagged relative to stock price that occurs tomorrow.  I just want to confirm that this reward will be for next day. 

Thanks

**Comment by AminHP** [comment]
Hi @ChiragMirani,

It is not explicitly specified. Based on the reward function, the agent learns to trade for 1 day ahead or more in different situations.

**Comment by ChiragMirani** [comment]
Thank you! very useful. I saw this in the code but just wanted to confirm.  

Best,
Chirag
