### ISSUE TITLE
How to maximize the sharpe ratio? 

### ISSUE THREAD

**Issue by GXY2017** [AminHP/gym-anytrading#62]
Current step_reward is linear and maximize step_reward will maximize the self._total_reward. 
But Sharpe ratio requires historical yield data, and maximizing the Sharpe ratio in each step may not get the best strategy for the whole training data. 
Do you have any idea to maximize Sharpe ratio?  Thank you.

**Comment by AminHP** [comment]
Hi @GXY2017 

First of all, the current reward function is just a simple example and does not consider everything.
The historical data is available in the `history` attribute in the trading env class. I think it contains all the required information you need.
