### ISSUE TITLE
trading_env step(action) returns previous observation

### ISSUE THREAD

**Issue by henrydeclety** [AminHP/gym-anytrading#66]
Going through your code for TradingEnv, something seems odd to me, the function step(action) is supposed to return the next observation right? 

In step(action), if it is using prices[self._current_tick] to calculate the reward given by action, the it should return the observation which contains the data point at self._current_tick right? In that case shouldn't get_observation be

```
def _get_observation(self):
        return self.signal_features[(self._current_tick-self.window_size+1):self._current_tick+1]
```

instead of 

```
def _get_observation(self):
        return self.signal_features[(self._current_tick-self.window_size):self._current_tick]
```
?

Thank you for your help

**Comment by GXY2017** [comment]
It only has two states. So, if the last action is long,  the agent will close it and sells at the same bar. I think your code will sell it at the next new bar.

**Comment by AminHP** [comment]
Hi @henrydeclety,

I think you are right. I had fixed the issue in my other repo but forgot to update it here. Thanks for noticing. I released a new version.
