### ISSUE TITLE
Run in win 10?

### ISSUE THREAD

**Issue by johanbech** [AminHP/gym-anytrading#69]
I have try everything in my power to run it in win 10 but can´t. every time something is not update or version is wrong, Try on python 3.6 and 3.7-3.9 nothing work
How do you do it. Do you use win 10 like me or linux? Do you use anaconda? can we get yours "Environments"..

**Comment by AminHP** [comment]
Hi @johanbech,

I just fixed a minor issue and tested the env in win 10 and it worked. My python version is 3.9.6 and I use pip. Please install the latest version of the project.
