### ISSUE TITLE
KeyError: 'render_modes' while creating 'stock-v0' environment

### ISSUE THREAD

**Issue by Olwar** [AminHP/gym-anytrading#71]
![image](https://user-images.githubusercontent.com/81160300/180601967-2df61773-4807-42cd-8281-1230e4be1ec1.png)

Don't know how to solve this.

I've tried so far: 
Deleted all the parameters
Tried to set render_mode="Human" and "rgb_array", "True" and "False" none of these work
Downgraded gym to 0.24.1 and 0.20.0

Whole code:
![image](https://user-images.githubusercontent.com/81160300/180602031-633e8020-8ecc-4dfe-b88d-bbb632b8ac33.png)

**Comment by AminHP** [comment]
Hi @Olwar,

In [this](https://github.com/AminHP/gym-anytrading/blob/master/gym_anytrading/envs/trading_env.py#L24) line of code, change `render.modes` to `render_modes`. I will make the project compatible with newer versions of gym and release a fixed version soon.

**Comment by Olwar** [comment]
Hey AminHP,

Thank you very much, that fixed the issue! Also thank you for this repository, it helps a lot.
