### ISSUE TITLE
why the price is based on 'Low' but not 'Close'

### ISSUE THREAD

**Issue by williamlifaith** [AminHP/gym-anytrading#77]
Hello,
in this line :prices = env.df.loc[:, 'Low'].to_numpy()[start:end]

I think we need replace 'Low' with 'Close',that will be better,may I know the reason why you use 'Low' here ?

**Comment by AminHP** [comment]
Hi @williamlifaith,

It is based on close price:
https://github.com/AminHP/gym-anytrading/blob/master/gym_anytrading/envs/stocks_env.py#L19
https://github.com/AminHP/gym-anytrading/blob/master/gym_anytrading/envs/forex_env.py#L20
