### ISSUE TITLE
only two actions short and long?

### ISSUE THREAD

**Issue by JiangjiaoLu** [AminHP/gym-anytrading#80]
in some circumstances, such as China A stock, 'hold' would be a must just because we are not free to buy and sell all the time. Would you please update an edition with three kinds of actions?

**Comment by AminHP** [comment]
Hi @JiangjiaoLu,
As I explained in previous issues, I decided to leave this project as is with two actions. In case you need 3 actions or more, you can use [this project](https://github.com/AminHP/gym-anytrading#related-projects). I also created another repo, [gym-mtsim](https://github.com/AminHP/gym-mtsim), which is a real-world simulator with precise calculations and continuous actions space.

**Comment by JiangjiaoLu** [comment]
I appreciate so much for your reply. Your [gym-mtsim](https://github.com/AminHP/gym-mtsim) is what I am looking for.

**Comment by AminHP** [comment]
You're welcome :)
