### ISSUE TITLE
On training how to set the frame_bound?

### ISSUE THREAD

**Issue by talvasconcelos** [AminHP/gym-anytrading#84]
I've been trying the stocksEnv on BTC data, to train a PPO agent. How do i set the frame_bound for training? it's the all training data, like `frame_bound=(window_size, len(train))` ? or i set a smaller "window" that the bot learns on randomly, `frame_bound=(window_size, 200)`?

**Comment by AminHP** [comment]
Both methods or even a combination of them can be appropriate. Depending on the data and problem, each can have its own advantages. I think they are both worth investigating.

**Comment by talvasconcelos** [comment]
Also, when taking the saved model and trying to use it on a python script, what's the minimum requeirements to use the model to make predictions? Do i need `gym` and `gym_anytrading` in order to create an env? when loading the model, do always need an env?
