### ISSUE TITLE
Feature Request: update from gym to gymnasium

### ISSUE THREAD

**Issue by elliottower** [AminHP/gym-anytrading#85]
Hi, this repository is currently listed in the gymnasium [third party environments](https://gymnasium.farama.org/environments/third_party_environments/) but we are cleaning the list up to only include maintained gymnasium-compatible repositories.  

Would it be possible for it to be upgraded from gym to gymnasium? [Gymnasium](https://github.com/Farama-Foundation/Gymnasium) is the maintained version of openai gym and is compatible with current RL training libraries ([rllib](https://github.com/ray-project/ray/tree/master/rllib) and [tianshou](https://github.com/thu-ml/tianshou) have already migrated, and [stable-baselines3](https://github.com/DLR-RM/stable-baselines3/blob/e5deeed16efb57c34ccdcb14692439154d970527/docs/guide/install.rst#bleeding-edge-version) will soon).  

For information about upgrading and compatibility, see [migration guide](https://gymnasium.farama.org/content/migration-guide/) and [gym compatibility](https://gymnasium.farama.org/content/gym_compatibility/). The main difference is the API has switched to returning `truncated` and `terminated`, rather than `done`, in order to give more information and mitigate edge case issues.

**Comment by Alex2782** [comment]
@AminHP: https://github.com/AminHP/gym-anytrading/pull/86     (update from gym to gymnasium)

I have followed some guidelines as in the example:
https://gymnasium.farama.org/tutorials/gymnasium_basics/environment_creation/

**Comment by brlocky** [comment]
@Alex2782 
Great work !

**Comment by AminHP** [comment]
I just released version v2.0.0 which is fully compatible with the latest gymnasium.
