### ISSUE TITLE
Unable to evaluate models

### ISSUE THREAD

**Issue by ShinyOrbThing** [AminHP/gym-anytrading#98]
I have trained an A2C model on some simulated stock data, following the same steps as are shown in [this notebook](https://github.com/nicknochnack/Reinforcement-Learning-for-Trading/blob/main/Reinforcement%20Learning%20GME%20Trading%20Tutorial.ipynb).

On the line containing "obs = obs[np.newaxis, ...]"

I get the following error:
TypeError: tuple indices must be integers or slices, not tuple

```python
env = gym.make('stocks-v0', df=df, frame_bound=(90,110), window_size=5)
obs = env.reset()

while True: 
    obs = obs[np.newaxis, ...]
    action, _states = model.predict(obs)
    obs, rewards, done, info = env.step(action)
    if done:
        print("info", info)
        break
```

**Comment by AminHP** [comment]
This code is based on an older version of gym-anytrading. You can install `gym-anytrading<2.0.0`, or change your code according to [these](https://github.com/AminHP/gym-anytrading/blob/master/examples) examples.

**Comment by ShinyOrbThing** [comment]
Thanks @AminHP.
